### PR TITLE
[Fix] `jsx-key`: catch key errors inside conditional statements

### LINKED ISSUE #3117: Eslint does not work if the jsx key is missed inconditions
Eslint does not work if the jsx key is missed in conditions

Screenshot:
image

Code:
```tsx
const Test = (): React.ReactNode => {
  const list = [1, 2, 3, 4, 5];

  return (
    <div>
      {list.map(item => {
        if (item < 2) {
          /* The eslint error didn't work: */
          return <div>{item}</div>;
        }

        return <div />;
      })}
    </div>
  );
};

```

### PR DESCRIPTION
**Pull request by TildaDares**
Fixes #3117

### CODE REVIEW

File: lib/rules/jsx-key.js [hunk 1]
```diff
@@ -86,8 +86,25 @@ module.exports = {
...
-    function getReturnStatement(body) {
-      return body.filter((item) => item.type === 'ReturnStatement')[0];
+    function getReturnStatements(node) {
+      const returnStatements = arguments[1] || [];
+      if (node.type === 'IfStatement') {
+        if (node.consequent) getReturnStatements(node.consequent, returnStatements);
+        if (node.alternate) getReturnStatements(node.alternate, returnStatements);
+      } else {
+        const body = node.body;
+        body.forEach((item) => {
```
Comment (ljharb) [inline lib/rules/jsx-key.js:96]:
```suggestion
        node.body.forEach((item) => {
```

File: lib/rules/jsx-key.js [hunk 2]
```diff
@@ -189,10 +206,12 @@ module.exports = {
 
         if (isFn || isArrFn) {
           if (fn.body.type === 'BlockStatement') {
-            const returnStatement = getReturnStatement(fn.body.body);
-            if (returnStatement && returnStatement.argument) {
-              checkIteratorElement(returnStatement.argument);
-            }
+            const returnStatements = getReturnStatements(fn.body);
+            returnStatements.forEach((returnStatement) => {
```
Comment (ljharb) [inline lib/rules/jsx-key.js:210]:
```suggestion
            getReturnStatements(fn.body).forEach((returnStatement) => {
```

**Review by ljharb — APPROVED** [review]
Looks great!
