### PR TITLE
[Fix] `no-unknown-property`: allow `abbr` on `<th>` and `<td>`

### LINKED ISSUE #3418: react/no-unknown-property: allow abbr on th
The `react/no-unknown-property` rule reports the `abbr` tag on `th` elements as invalid, which seems incorrect: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/th#attr-abbr

### PR DESCRIPTION
**Pull request by OleksiiKachan**
Fixes #3418

[https://www.w3resource.com/html/attributes/html-abbr-attribute.php]()

### CODE REVIEW

File: tests/lib/rules/no-unknown-property.js [hunk 1]
```diff
@@ -46,29 +46,41 @@ ruleTester.run('no-unknown-property', rule, {
     { code: '<div onMouseDown={this._onMouseDown}></div>;' },
     { code: '<a href="someLink" download="foo">Read more</a>' },
     { code: '<area download="foo" />' },
-    { code: '<img src="cat_keyboard.jpeg" alt="A cat sleeping on a keyboard" />' },
+    {
+      code: '<img src="cat_keyboard.jpeg" alt="A cat sleeping on a keyboard" />',
+    },
```
Comment (ljharb) [inline tests/lib/rules/no-unknown-property.js:51]: i'm not sure what these unrelated formatting changes are - just in case, please be sure to only run prettier on projects that have it configured. it's incorrect to run a formatter on a project that's not part of the project already.

**Review by ljharb — APPROVED** [review]
rebased and reverted the unrelated formatting changes
