### PR TITLE
[Fix] `destructuring-assignment`: fix false negative when using typeof props.a

### LINKED ISSUE #3828: [Bug]: react/destructuring-assignment inconsistent behavior
### Is there an existing issue for this?

- [X] I have searched the existing issues and my issue is unique
- [X] My issue appears in the command-line and not only in the text editor

### Brief description

It appears the `react/destructuring-assignment` rule is not behaving consistently with type definitions.

### Code example
```tsx
type Props = { text: string };
export const MyComponent: React.FC<Props> = (props) => {
  return <div>{props.text}</div>;
  //           ^^^^^^^^^^
};

export const MyOtherComponent: React.FC<Props> = (props) => {
  const { text } = props;
  type MyType = typeof props.text;
  return <div>{text as MyType}</div>;
};
```

### What is happening? / What is the error?
- In `MyComponent`, linter gives a `react/destructuring-assignment` error.
- In `MyOtherComponent` linter stays silent.

To me this appears as an unexpected inconsistency.

### What command(s) did you run to reproduce issue?
Using the code example above;
```sh
npx eslint ./eslint-test.tsx
```

### Expected Behavior

I would expect both components to trigger the linter rule.

### eslint-plugin-react version

v7.34.3

### eslint version

v8.57.0

### node version

v18.20.2

### PR DESCRIPTION
**Pull request by golopot**
Fixes #3828 

The rule failed to catch usages of `typeof props.a` because it is parsed a TSQualifiedName instead of a memberExpression.

### CODE REVIEW

File: tests/lib/rules/destructuring-assignment.js [hunk 1]
```diff
@@ -882,10 +882,16 @@ ${'            '}
         };
       `,
       options: ['always', { destructureInSignature: 'always' }],
-      features: ['types'],
+      features: ['types', 'no-babel'],
```
Comment (ljharb) [inline tests/lib/rules/destructuring-assignment.js:885]: we should still be testing the pre-existing test cases against the babel parser.

File: lib/rules/destructuring-assignment.js [hunk 2]
```diff
@@ -196,12 +215,7 @@ module.exports = {
       'FunctionExpression:exit': handleStatelessComponentExit,
 
       MemberExpression(node) {
-        let scope = getScope(context, node);
-        let SFCComponent = components.get(scope.block);
-        while (!SFCComponent && scope.upper && scope.upper !== scope) {
-          SFCComponent = components.get(scope.upper.block);
-          scope = scope.upper;
-        }
```
Comment (ljharb) [inline lib/rules/destructuring-assignment.js:204]: i think we still need this; we support Flow as well as many versions of TS.

File: tests/lib/rules/destructuring-assignment.js (hunk 1 above)
Comment (golopot) [reply tests/lib/rules/destructuring-assignment.js:885]: I changed the destination branch from issue-3828 to master.

**Review by ljharb — APPROVED** [review]
awesome, thanks! i'll get this landed in the next day or two.
