### PR TITLE
[Fix] `jsx-no-leaked-render`: invalid report if left side is boolean

### LINKED ISSUE #3719: [Bug]: `jsx-no-leaked-render` report `&&` in prop
### Is there an existing issue for this?

- [X] I have searched the existing issues and my issue is unique
- [X] My issue appears in the command-line and not only in the text editor

### Description Overview

Imagine you have a prop (e.g. `isOpen`), you want to set the value as `firstCondition === true && anotherCondition === true`. Currently the plugin report wrongly this kind of code which should be valid.

image

### Expected Behavior

I expect to not throw

### eslint-plugin-react version

7.34.1

### eslint version

8.57.0

### node version

18

### PR DESCRIPTION
**Pull request by akulsr0**
Closes #3719

### CODE REVIEW

**Comment by akulsr0** [comment]
Can we rerun the failing tests once?

File: lib/rules/jsx-no-leaked-render.js [hunk 1]
```diff
@@ -160,6 +161,18 @@ module.exports = {
...
           }
+          const variables = variableUtil.variablesInScope(context);
+          const leftSideVar = variableUtil.getVariable(variables, leftSide.name);
+          if (leftSideVar) {
+            const leftSideValue = leftSideVar.defs
+              && leftSideVar.defs.length
+              && leftSideVar.defs[0].node.init
+              && leftSideVar.defs[0].node.init.value;
+            const leftSideType = typeof leftSideValue;
+            if (leftSideType === 'boolean') {
```
Comment (ljharb) [inline lib/rules/jsx-no-leaked-render.js:172]:
```suggestion
            if (typeof leftSideValue === 'boolean') {
```
this actually bypasses engine optimizations sometimes, and the extra variable isn't really adding value.

**Comment by ljharb** [comment]
Don't worry about the Automatic Rebase check, and the code coverage check isn't a "failure" as much as an indicator that this PR drops the coverage percentage.

**Review by ljharb — APPROVED** [review]
