### PR TITLE
[Fix] `jsx-no-leaked-render`: preserve RHS parens for multiline jsx element while fixing

### LINKED ISSUE #3551: [Bug]: Excessive code changes done by --fix react/jsx-no-leaked-render
### Is there an existing issue for this?

- [X] I have searched the existing issues and my issue is unique
- [X] My issue appears in the command-line and not only in the text editor

### Description Overview

When using `'react/jsx-no-leaked-render': ['error', { validStrategies: ['coerce', 'ternary'] }],` and running `eslint --fix` the resulting code changes go beyond what's required for the actual fix by also removing parentheses, causing excessive code diffs.

Screenshot 2023-03-17 at 9 03 07 PM

I would expect the second hunk to be a single line change, just like the first hunk. Running this fix across a large codebase is unfeasible because the changes cannot be human-verified.

`eslint --fix` with `'react/jsx-no-leaked-render': ['error', { validStrategies: ['coerce', 'ternary'] }],`

### Expected Behavior

I'd expect no parentheses would be removed and no code-style to change. Other than the `!!` required to fix the issue, nothing else at all should change in the code.

Screenshot 2023-03-17 at 9 09 34 PM

### eslint-plugin-react version

7.21.5

### eslint version

8.35.0

### node version

16.13.1

### PR DESCRIPTION
**Pull request by akulsr0**
Fixes #3551

### CODE REVIEW

File: lib/rules/jsx-no-leaked-render.js [hunk 1]
```diff
@@ -82,6 +82,15 @@ function ruleFixer(context, fixStrategy, fixer, reportedNode, leftNode, rightNod
     if (rightNode.type === 'ConditionalExpression') {
       return fixer.replaceText(reportedNode, `${newText} && (${rightSideText})`);
     }
+    if (rightNode.type === 'JSXElement') {
+      const rightSideTextLines = rightSideText.split('\n');
+      if (rightSideTextLines.length > 1) {
+        const rightSideTextLastLine = rightSideTextLines[rightSideTextLines.length - 1];
+        const indentSpacesStart = Array(rightSideTextLastLine.search(/\S/)).fill(' ').join('');
```
Comment (ljharb) [inline lib/rules/jsx-no-leaked-render.js:89]: let’s use string repeat here instead of array/fill/join, esp since Array() should never be used.

**Review by ljharb — APPROVED** [review]
Looks great, thanks!
