### PR TITLE
[Fix] `prop-types`: handle nested forwardRef + memo

### LINKED ISSUE #3521: [Bug]: Error react/prop-types , although the type has been specified
### Is there an existing issue for this?

- [X] I have searched the existing issues and my issue is unique
- [x] My issue appears in the command-line and not only in the text editor

### Description Overview

Error react/prop-types , although the type has been specified

this is error:
```javascript
import React, { forwardRef, memo } from 'react';

interface Props1 {
    age: number;
}
export const Hello = memo(
    forwardRef(({ age }: Props1) => { // error: 'age' is missing in props validationeslint(react/prop-types)
        return <div>Hello {age}</div>;
    }),
);
```

but this is correct:
```javascript
import React, { forwardRef, memo } from 'react';

interface Props1 {
    age: number;
}
const HelloTemp = forwardRef(({ age }: Props1) => {
    return <div>Hello {age}</div>;
});
export const Hello = memo(HelloTemp);
```

### Expected Behavior

Expected  no error

### eslint-plugin-react version

v7.30.1

### eslint version

v8.29.0

### node version

v16.19.0

### PR DESCRIPTION
**Pull request by developer-bandi**
Fix #3521

- Modified to allow an exception that skips the type check of memo when forwardRef and memo are nested.
- forwardRef, memo, forwardRef with memo testcase add

### CODE REVIEW

**Review by ljharb — APPROVED** [review]

**Comment by ljharb** [comment]
With the latest rebase, some tests are failing. Can you update to this commit and take a look?

**Comment by developer-bandi** [comment]
yes, so I fix the failed test code but almost code is changed. so may be reivew is nessesary

and some Tests are fail because node install fail. i don't know why it is fail. please tell me hint to fix it. (and Automatic Rebase)

File: lib/rules/prop-types.js [hunk 1]
```diff
@@ -186,13 +186,34 @@ module.exports = {
...
+     * @param {Array} list The all components to process
+     * @returns {Boolean} True if the component is nested False if not.
+     */
+    function checkNestedComponent(component, list) {
+      const componentIsMemo = component.node.callee && component.node.callee.name === 'memo';
+      const argumentIsForwardRef = component.node.arguments && component.node.arguments[0].callee && component.node.arguments[0].callee.name === 'forwardRef';
+      if (componentIsMemo && argumentIsForwardRef) {
+        const forwardComponent = list.find(
+          (innerComponent) => innerComponent.node.range[0] === component.node.arguments[0].range[0]
+            && innerComponent.node.range[0] === component.node.arguments[0].range[0]);
```
Comment (ljharb) [inline lib/rules/prop-types.js:200]:
```suggestion
      if (componentIsMemo && argumentIsForwardRef) {
        const forwardComponent = list.find(
          (innerComponent) => (
            innerComponent.node.range[0] === component.node.arguments[0].range[0]
            && innerComponent.node.range[0] === component.node.arguments[0].range[0]
        );
```

**Review by ljharb — CHANGES_REQUESTED** [review]
You don't have to worry about the automatic rebase check. The PR now lacks any tests, is that intentional?

**Comment by developer-bandi** [comment]
> You don't have to worry about the automatic rebase check. The PR now lacks any tests, is that intentional?

no, it is not intentional. it's my mistake. perhaps i did 풀 at local codebase, that test code is deleted.
so i revert all test code already exist

**Comment by developer-bandi** [comment]
@ljharb 
Is there anything additional I need to do to merge this pr?

**Review by ljharb — APPROVED** [review]
