### PR TITLE
[New] export flat configs from plugin root and fix flat config crash

### LINKED ISSUE #3693: [Bug]: flat config crash when using manual plugin def and recommended config
### Is there an existing issue for this?

- [X] I have searched the existing issues and my issue is unique
- [X] My issue appears in the command-line and not only in the text editor

### Description Overview

# Repro

```js
// eslint.config.js
import eslintReact from 'eslint-plugin-react';
import eslintReactRecommended from 'eslint-plugin-react/configs/recommended.js';

export default [
	{
		plugins: {
			react: eslintReact,
		},
	},
	eslintReactRecommended,
];
```

`npx eslint eslint.config.js`

# Expected

No errors

# Actual

```
Oops! Something went wrong! :(

ESLint: 8.56.0

Error: Key "plugins": Cannot redefine plugin "react".
```

# More Info

When defining a plugin key in the flat config ESLint enforces that you only ever redefine they key with the same plugin. [This check is done by comparing by reference](https://github.com/eslint/eslint/blob/8e13a6beb587e624cc95ae16eefe503ad024b11b/lib/config/flat-config-schema.js#L361-L363) -- i.e. `configA.plugin.react === configB.plugin.react`

`eslint-plugin-react` fails this check because it defines its "plugin" in two locations:
https://github.com/jsx-eslint/eslint-plugin-react/blob/36e791de784e7fa1edd5b6d232fbcaf2dd7cf9bf/index.js#L14-L31
https://github.com/jsx-eslint/eslint-plugin-react/blob/36e791de784e7fa1edd5b6d232fbcaf2dd7cf9bf/configs/all.js#L23-L26

For this to work there needs to be exactly 1 copy of the "plugin" defined by the package.
For example:
```js
const plugin = { ... };
plugin.configs = {
  recommended: {
    plugins: { react: plugin },
    rules: { ... },
  },
  all: {
    plugins: { react: plugin },
    rules: { ... },
  },
});
```

### eslint-plugin-react version

v7.33.2

### eslint version

v8.56.0

### node version

v20.11.0

### PR DESCRIPTION
**Pull request by bradzacher**
fixes #3693

This PR exposes the flat configs at the root of the plugin:
```js
const reactPlugin = require('eslint-plugin-react');

module.exports = [
  // ...
  reactPlugin.configs['flat/recommended'],
  // ...
];
```

The `flat/` prefix is an approach a number of plugins are taking to enable supporting both styles at the top-level.

---

This was the easiest way to set things up so that the plugin reference was consistent across the root and all configs.

I'm open to a different approach to fixing the issue - for example if you want to ensure the `config/` exports all work as well - it's just going to be a much larger refactor to make that work because we need to restructure the configs so there isn't a cyclic dependency between the configs and the plugin.

*Personally* I'm of the opinion that this "everything from the root" approach offers better DevX compared to forcing users to separately import the configs. It's a stylistic thing though - up to you really.

### CODE REVIEW

**Comment by ljharb** [comment]
hmm - i definitely prefer deep imports; barrel files/manifest exports cause all sorts of problems.

how would the refactor work to have flat configs not be at the root?

**Comment by bradzacher** [comment]
> how would the refactor work to have flat configs not be at the root?

An example of a plugin that goes your deep import approach is https://github.com/eslint-community/eslint-plugin-eslint-plugin/

They define the flat configs as a function of the legacy configs.

EG
```js
const plugin = require('../index');

module.exports = {
  plugins: { react: plugin },
  rules: plugin.configs.recommended.rules,
};
```

But their usecase is a bit simpler as it doesn't need to worry about language options etc.

**Comment by ljharb** [comment]
I've rebased this; i'm still hopeful for a way to have the root be the current legacy config, in particular to avoid a breaking change.

**Comment by jakec-dev** [comment]
Any update on this? This plugin is unusable with Airbnb config until this is pulled

**Comment by ljharb** [comment]
@jakec-dev the airbnb config doesn't use flat config, so it should be perfectly usable if you use a compatible version of eslint (not 9, yet) and the default config format of the supported eslint versions (eslintrc)

**Comment by mdjermanovic** [comment]
> I've rebased this; i'm still hopeful for a way to have the root be the current legacy config, in particular to avoid a breaking change.

It isn't a problem for either of the two config systems (eslintrc and flat) to include both config formats in `configs`, with different keys of course. Eslintrc users would keep using the same configs (no breaking changes) and flat config users would be using the new configs (`reactPlugin.configs['flat/recommended']` as in the original post).

**Comment by mdjermanovic** [comment]
On the other hand, if you prefer deep imports, a solution could be to invert https://github.com/jsx-eslint/eslint-plugin-react/commit/17858beeedaaf5d0eb4fd1cc292fb34d07f9f659: move rule configs and parserOptions back to `index.js` and update `configs/recommended.js` and others to load `index.js` and translate configs into the flat config format.

**Comment by mdjermanovic** [comment]
Also relevant: https://github.com/eslint/eslint/issues/18095

**Comment by ljharb** [comment]
I vastly prefer deep imports, for both eslintrc and flat.

If we can use those, and ensure no breakage for existing eslintrc users, then that sounds like a great solution to get this over the line.

**Comment by mdjermanovic** [comment]
> I vastly prefer deep imports, for both eslintrc and flat.
> 
> If we can use those, and ensure no breakage for existing eslintrc users, then that sounds like a great solution to get this over the line.

eslintrc config system doesn't provide a way for plugins to export configs other than under the `configs` key, so there's probably no point in adding new (deep) exports for eslintrc configs.

As for flat configs, this is doable as @bradzacher suggested in https://github.com/jsx-eslint/eslint-plugin-react/pull/3694#issuecomment-1958261297. Technically, it could be implemented as suggested in https://github.com/jsx-eslint/eslint-plugin-react/pull/3694#issuecomment-2163881696.

**Comment by ljharb** [comment]
Sounds great, let's do that :-)

If you drop a link to a sha or branch here, i can pull it into this PR

**Comment by mdjermanovic** [comment]
Here's the branch:

https://github.com/mdjermanovic/eslint-plugin-react/tree/fix-flat-configs

* https://github.com/mdjermanovic/eslint-plugin-react/commit/31ef12a6becd39ef899773f3a0ab64cb0c50d5da fixes this problem.
* https://github.com/mdjermanovic/eslint-plugin-react/commit/740bf7c1bc0af7301cc72dfcdcceacfa9f968191 adds tests.

I'm not sure why `languageOptions` in configs were set non-enumerable, but changing that would probably be a breaking change.

**Comment by ljharb** [comment]
It was set that way because eslint threw when it was enumerable - i forget whether it threw with eslintrc, or with flat config, but making it nonenumerable hid it from one and allowed the other to read it.

**Comment by ljharb** [comment]
@mdjermanovic hm, those two commits are on top of master, not this PR, and there's a conflict. I've rebased this PR; can you stack your commits on top of it, and then I can pull them in?

**Comment by mdjermanovic** [comment]
@ljharb to clarify, do you want eslint-plugin-react to provide two ways to use its flat configs?

1st:

```js
const reactRecommended = require('eslint-plugin-react/configs/recommended');

module.exports = [
  reactRecommended
];
```

2nd:

```js
const reactPlugin = require('eslint-plugin-react');

module.exports = [
  reactPlugin.configs['flat/recommended']
];
```

**Comment by ljharb** [comment]
I’m comfortable with that, as long as it doesn’t introduce cycles - but it’d also be sufficient to only have the deep import way (but it should say “flat” somewhere in there)

**Comment by mdjermanovic** [comment]
Here's a branch on top of this PR. It keeps flat configs in plugin root (those added in this PR), fixes existing flat configs intended for deep imports, and adds tests for both:

https://github.com/mdjermanovic/eslint-plugin-react/tree/fix-deep-flat-configs

File: index.js [hunk 1]
```diff
@@ -1,31 +1,109 @@
...
+  plugins: { react: plugin },
+  rules: plugin.configs.all.rules,
+  languageOptions: { parserOptions: plugin.configs.all.parserOptions },
+};
+
+plugin.configs['flat/jsx-runtime'] = {
+  plugins: { react: plugin },
+  rules: plugin.configs['jsx-runtime'].rules,
+  languageOptions: { parserOptions: plugin.configs['jsx-runtime'].parserOptions },
+};
```
Comment (ljharb) [inline index.js:107]: this might be more ergonomic if it's a "flat" object with 3 properties, "recommended", "all", "jsx-runtime"?

File: tests/flat-config.js [hunk 2]
```diff
@@ -0,0 +1,117 @@
+/* eslint-env mocha */
+
+'use strict';
+
+const semver = require('semver');
+const eslintPkg = require('eslint/package.json');
+
+if (!semver.satisfies(eslintPkg.version, '>= 8.57.0')) {
+  return;
+}
```
Comment (ljharb) [inline tests/flat-config.js:10]: flat config wasn't added in 8.57; is there a reason this isn't targeting the first version of 8 that has flat config?

File: index.js (hunk 1 above)
Comment (mdjermanovic) [reply index.js:107]: Unlike eslintrc, there are no restrictions on how flat configs can be exported from plugins. However, the convention ESLint recommends is to still export configs as properties of `configs` (https://github.com/eslint/eslint/issues/18095).

File: tests/flat-config.js (hunk 2 above)
Comment (ljharb) [reply tests/flat-config.js:10]: cool, i can do that.

File: index.js (hunk 1 above)
Comment (mdjermanovic) [reply index.js:107]: Sounds good to me at the moment.

In some future major version of this plugin, it would be good to switch to:

 `{ configs: { 'legacy/recommended' /* eslintrc */, 'recommended' /* flat */, ... } }`

Comment (ljharb) [reply index.js:107]: certainly, if indeed the ecosystem prefers flat config then there will come a time when it doesn't make sense to support anything prior to that.

Comment (mdjermanovic) [reply index.js:107]: Here's a commit that updates this: https://github.com/mdjermanovic/eslint-plugin-react/commit/bbdaaa7f50303a9a8febf81f03f801af84c3f82e

File: tests/flat-config.js (hunk 2 above)
Comment (mdjermanovic) [reply tests/flat-config.js:10]: Here's also a commit that updates this: https://github.com/mdjermanovic/eslint-plugin-react/commit/2f28188a12e4f2657276641b842cd2d9f01fe744

File: index.js (hunk 1 above)
Comment (mdjermanovic) [reply index.js:107]: Anything else I could to help finish this?

**Comment by ljharb** [comment]
Sorry for the delays. I've pulled in the two commits and rebased.

I'll give it another full rereview now, and if CI passes and the only remaining comments are minor, I'll update the PR and land it.

File: README.md [hunk 3]
```diff
@@ -203,27 +203,22 @@ Refer to the [official docs](https://eslint.org/docs/latest/user-guide/configuri
...
 
 <!-- markdownlint-disable-next-line no-duplicate-heading -->
-### Shareable configs
-
-There're also 3 shareable configs.
-
-- `eslint-plugin-react/configs/all`
-- `eslint-plugin-react/configs/recommended`
-- `eslint-plugin-react/configs/jsx-runtime`
+### Flat Configs
```
Comment (ljharb) [inline README.md:207]: it seems like we need an "eslintrc Configs" or "Legacy Configs" section, that preserves the non-flat examples?

File: configs/all.js [hunk 4]
```diff
@@ -1,49 +1,13 @@
...
-        jsx: true,
-      },
-    },
-  },
+  plugins: { react: plugin },
+  rules: legacyConfig.rules,
+  languageOptions: { parserOptions: legacyConfig.parserOptions },
 };
 
-// this is so the `languageOptions` property won't be warned in the new config system
```
Comment (ljharb) [inline configs/all.js:48]: should we keep this comment, since it still applies?

File: configs/jsx-runtime.js [hunk 5]
```diff
@@ -1,18 +1,13 @@
 'use strict';
 
-const all = require('./all');
+const plugin = require('../index');
```
Comment (ljharb) [inline configs/jsx-runtime.js:3]:
```suggestion
const plugin = require('../');
```

File: configs/all.js [hunk 6]
```diff
@@ -1,49 +1,13 @@
 'use strict';
 
-const fromEntries = require('object.fromentries');
-const entries = require('object.entries');
+const plugin = require('../index');
```
Comment (ljharb) [inline configs/all.js:3]:
```suggestion
const plugin = require('../');
```

File: configs/recommended.js [hunk 7]
```diff
@@ -1,34 +1,13 @@
 'use strict';
 
-const all = require('./all');
+const plugin = require('../index');
```
Comment (ljharb) [inline configs/recommended.js:3]:
```suggestion
const plugin = require('../');
```

**Review by ljharb — APPROVED** [review]

File: README.md (hunk 3 above)
Comment (mdjermanovic) [reply README.md:207]: I believe the section for eslintrc configs is still in the document:

https://github.com/jsx-eslint/eslint-plugin-react/blob/eb4d749f0236b8e7a80d15755701426206085ea9/README.md#shareable-configs

File: configs/all.js (hunk 4 above)
Comment (mdjermanovic) [reply configs/all.js:48]: This comment was confusing. I think it should have been "this is so the languageOptions property won't be warned in the _old_ config system" (because the properties of this config were copied into the eslintrc config [here](https://github.com/jsx-eslint/eslint-plugin-react/blob/67d73aa0b7eed389ce5e9b6ce2ce38660c2676ae/index.js#L22-L25)). If that's the case, I believe this comment no longer applies because this config isn't used to build the equivalent eslintrc config anymore.

File: README.md (hunk 3 above)
Comment (ljharb) [reply README.md:207]: aha, thanks, i must have missed it in the diff view.
