### PR TITLE
[Fix] `display-name`: fix false positive for HOF returning only nulls and literals

### LINKED ISSUE #3300: False-positive for react/display-name after 7.29.4 → 7.30.0 upgrade
After upgrading eslint-plugin-react from 7.29.4 to 7.30.0 a new linting error appeared in my project that doesn't seem right. My project is a big full-stack monolith web app and it contains both Vue.js and React.js code. Now I am getting `react/display-name` for some Vue/Vuex code that has nothing to do with React. I stripped down the file, the original was much longer, but this still triggers the error:

```js
import Vuex from 'vuex'
import Vue from 'vue'

// code omitted

const getters = {
  getChat: state => (scopePath, partnerId) => {
    const selectedChatScope = state.chats && state.chats.find(chat => chat.path === scopePath)

    if (!selectedChatScope) {
      return null
    }

    return 'something'
  }
}

export {
  getters
}
```

```
  7:21  error  Component definition is missing display name  react/display-name
```

### PR DESCRIPTION
**Pull request by golopot**
Fixes #3300.

This bug is caused by #3276.

Stop considering the following a component:
```js
const f = (a) => () => {
  if (a) {
    return null;
  }
  return 1;
};
```

The bug is triggered when a literal like `1` or `"a"` is returned somewhere.

### CODE REVIEW

File: tests/lib/rules/no-this-in-sfc.js [hunk 1]
```diff
@@ -275,58 +275,5 @@ ruleTester.run('no-this-in-sfc', rule, {
...
-          bar() {
-            () => () => {
-              this.something();
-              return null;
-            };
-          }
-        }
-      `,
-      errors: [{ messageId: 'noThisInSFC' }],
-    },
```
Comment (golopot) [inline tests/lib/rules/no-this-in-sfc.js:330]: These tests fails after this change.

**Review by ljharb — APPROVED** [review]

**Comment by ljharb** [comment]
Looks like after a rebase, there's some tests failing.

**Comment by golopot** [comment]
I have rebased the PR and removed some tests from the incoming commits.

**Review by ljharb — APPROVED** [review]

**Review by SiljeAlice — APPROVED** [review]
Good
