### PR TITLE
[Fix] `jsx-no-constructed-context-values`: detect constructed context values in React 19 `<Context>` usage

### LINKED ISSUE #3888: [Bug]: `jsx-no-constructed-context-values` doesn't detect issues when context is used as provider in react v19
### Is there an existing issue for this?

- [x] I have searched the existing issues and my issue is unique
- [x] My issue appears in the command-line and not only in the text editor

### Description Overview

In React 19, you can render `<Context>` as a provider instead of `<Context.Provider>`.

However when doing so `jsx-no-constructed-context-values` doesn't detect violations.

```tsx
const MyContext = createContext();

function MyComponent(props) {
  return (<>
    {/* old style - violation detected */ }
    <MyContext.Provider value={{ hello: 'world' }} />
    
    {/* react 19 style - no violation */ }
    <MyContext value={{ hello: 'world' }} />
  </>);
}

```

### eslint-plugin-react version

v7.37.2

### eslint version

v8.57.1

### node version

v18.20.6

### PR DESCRIPTION
**Pull request by TildaDares**
Fixes #3888 

This PR updates the `jsx-no-constructed-context-values` rule to support React 19-style context providers using the <Context> shorthand.

### CODE REVIEW

**Review by ljharb — CHANGES_REQUESTED** [review]
there's an uncovered line

**Comment by TildaDares** [comment]
The codecov check is stuck, so I can't confirm if the coverage has improved. Is there a way to rerun it?

**Comment by ljharb** [comment]
I had to rebase it anyways, so no worries :-) hopefully it won't be stuck this time. Thanks!

**Review by ljharb — APPROVED** [review]

File: lib/rules/jsx-no-constructed-context-values.js [hunk 1]
```diff
@@ -119,6 +119,45 @@ function isConstruction(node, callScope) {
...
+
+  if (!variableScoping) { // Context was not found in scope
+    return false;
+  }
+
+  // Get the variable's definition
+  const def = variableScoping.defs[0];
+
+  if (!def || def.node.type !== 'VariableDeclarator') {
+    return false;
```
Comment (ljharb) [inline lib/rules/jsx-no-constructed-context-values.js:140]: looks like we need a test for this if check

Comment (TildaDares) [reply lib/rules/jsx-no-constructed-context-values.js:140]: Resolved!

Comment (ljharb) [reply lib/rules/jsx-no-constructed-context-values.js:140]: hm, seems like there's still no coverage, but maybe i rebased it out. can you take another look?

File: docs/rules/jsx-no-constructed-context-values.md [hunk 2]
```diff
@@ -33,6 +43,11 @@ return (
 )
 ```
 
+```jsx
+const SomeContext = createContext();
+const Component = () => <SomeContext value="Some string"><SomeContext>;
```
Comment (jens-duttke) [inline docs/rules/jsx-no-constructed-context-values.md:48]: There's a slash missing in closing `<SomeContext>` -> `</SomeContext>`.
