### PR TITLE
[Fix] `jsx-no-literals`: properly error on children with noAttributeStrings: true

### LINKED ISSUE #3171: [`jsx-no-literals`]: no errors for children when `noAttributeStrings: true`
```js
'react/jsx-no-literals': [2, { noAttributeStrings: true }],
```

```js
import React from 'react';

export const WithAttributes = ({}) => <div title="foo bar" />;
export const WithChildren = ({}) => <div>baz bob</div>;
export const WithAttributesAndChildren = ({}) => (
  <div title="foo bar">baz bob</div>
);

```

Expected: the JSX inside of `WithChildren` produces an error (like it does when `noAttributeStrings: false`)

Actual: the JSX inside of `WithChildren` does not produce an error

### PR DESCRIPTION
**Pull request by TildaDares**
Fixes #3171

### CODE REVIEW

File: lib/rules/jsx-no-literals.js [hunk 1]
```diff
@@ -69,8 +69,8 @@ module.exports = {
     const config = Object.assign({}, defaults, context.options[0] || {});
     config.allowedStrings = new Set(config.allowedStrings.map(trimIfString));
 
-    function defaultMessageId() {
-      if (config.noAttributeStrings) {
+    function defaultMessageId(ancestorIsJSXElement = false) {
```
Comment (ljharb) [inline lib/rules/jsx-no-literals.js:72]: default arguments don't work in node 4
```suggestion
    function defaultMessageId() {
      const ancestorIsJSXElement = arguments.length > 1 && arguments[0];
```

File: tests/lib/rules/jsx-no-literals.js [hunk 2]
```diff
@@ -613,5 +613,41 @@ ruleTester.run('jsx-no-literals', rule, {
...
+        {
+          messageId: 'noStringsInAttributes',
+          data: { text: '"foo bar"' },
+        },
+      ],
+    },
+    {
+      code: `export const WithAttributesAndChildren = ({}) => (
+              <div title="foo bar">baz bob</div>
+            );`,
```
Comment (ljharb) [inline tests/lib/rules/jsx-no-literals.js:639]:
```suggestion
      code: `
        export const WithAttributesAndChildren = ({}) => (
          <div title="foo bar">baz bob</div>
        );
      `,
```

**Review by ljharb — CHANGES_REQUESTED** [review]
Looks good!

**Comment by ljharb** [comment]
Looks like some of the new test cases are expecting the wrong error message?

**Review by ljharb — APPROVED** [review]
