### PR TITLE
[Fix] `display-name`: Accept forwardRef and Memo nesting in newer React versions

### LINKED ISSUE #2954: display-name has false positive on nested use of memo and forwardRef
Since #2399, `eslint-plugin-react` knows not to complain about code like this:

```tsx
export const ComponentWithMemo = React.memo(function Component({ world }) {
 return <div>Hello {world}</div>
})

export const ComponentWithForwardRef = React.forwardRef(function Component({ world }) {
  return <div>Hello {world}</div>
})
```

In that pull request, nested use of `memo` and `forwardRef` like so...

```tsx
export const ComponentWithForwardRef = React.memo(React.forwardRef(function Component({ world }) {
  return <div>Hello {world}</div>
}))
```

...was intentionally treated as a `display-name` violation due to [a React bug causing such components to be anonymous](https://github.com/facebook/react/issues/16722). This issue was [solved in November 2019](https://github.com/facebook/react/pull/17274), so the `display-name` should now accept this.

### PR DESCRIPTION
**Pull request by TildaDares**
Fixes #2954

### CODE REVIEW

File: lib/rules/display-name.js [hunk 1]
```diff
@@ -58,11 +59,27 @@ module.exports = {
...
     }
 
+    /**
+     * Checks if React.forwardRef is nested inside React.memo
+     * @param {ASTNode} node The AST node being checked.
+     * @returns {Boolean} True if React.forwardRef is nested inside React.memo, false if not.
+     */
+    function isNestedMemo(node) {
+      return node.type === 'CallExpression'
+        && node.arguments[0].type === 'CallExpression'
```
Comment (ljharb) [inline lib/rules/display-name.js:69]: what if it's a call expression with no arguments?

File: lib/rules/display-name.js [hunk 2]
```diff
@@ -58,11 +59,27 @@ module.exports = {
...
+        && utils.isPragmaComponentWrapper(node);
+    }
+
     /**
      * Reports missing display name for a given component
      * @param {Object} component The component to process
      */
     function reportMissingDisplayName(component) {
+      if (isNestedMemo(component.node)
+        && testReactVersion(context, '0.14.10 || 15.7.0 || >= 16.12.0')) {
```
Comment (ljharb) [inline lib/rules/display-name.js:79]:
```suggestion
      if (
        isNestedMemo(component.node)
        && testReactVersion(context, '^0.14.10 || ^15.7.0 || >= 16.12.0')
      ) {
```

**Review by ljharb — CHANGES_REQUESTED** [review]
Let's also add some test cases for v0.14.11, v15.7.1, and v16.12.1

File: lib/rules/display-name.js [hunk 3]
```diff
@@ -65,8 +65,11 @@ module.exports = {
      * @returns {Boolean} True if React.forwardRef is nested inside React.memo, false if not.
      */
     function isNestedMemo(node) {
+      const argumentIsCallExpression = node.arguments && node.arguments[0]
+        ? node.arguments[0].type === 'CallExpression' : false;
```
Comment (ljharb) [inline lib/rules/display-name.js:69]:
```suggestion
      const argumentIsCallExpression = node.arguments && node.arguments[0] && node.arguments[0].type === 'CallExpression';
```

**Review by ljharb — APPROVED** [review]
