### PR TITLE
[Fix] `jsx-newline`: No newline between comments and jsx elements

### LINKED ISSUE #3478: `jsx-newline` puts line breaks between comments and new JSX elements
I have the `jsx-newline` rule turned on, which when run with the `--fix` option, puts line breaks between any comments (including eslint-disable comments) and JSX elements, thus undoing the whole point of using comments. 

Let's say I have something like this:

```jsx
<Element as="header" marginBottom="micro">
        {/* eslint-disable-next-line react/jsx-sort-props */}
        <Heading as="h6" align="right">
            Transaction value
        </Heading>
<Element>
```

The `jsx-newline` rule puts a line break between the eslint-disable comment and <Heading />, therefore causing the `eslint-disable-{some rule}` to stop working.

Can we handle putting line breaks between comments & new JSX elements?

I saw something similar in #2926 (which was closed earlier as completed) but that doesn't work properly as of `v7.31.10`

### PR DESCRIPTION
**Pull request by justmejulian**
Fixes #3478 and  #2926 and adds a couple more tests to show what was failing.

From what I can gather this should be the default behaviour. If not then then this can be hidden behind an option.

I was not sure about the behaviour of multiple Block comments before a Multiline Component. Decided the comments should stick together, based on sujan-s comment in #3478.

### CODE REVIEW

File: tests/lib/rules/jsx-newline.js [hunk 1]
```diff
@@ -105,6 +105,43 @@ new RuleTester({ parserOptions }).run('jsx-newline', rule, {
...
+        <Button popoverOpen='#settings-popover' style={{ width: 'fit-content' }}>
+          {/* fake-eslint-disable-next-line should also work insinde a component */}
+          <Icon f7='gear' />
+        </Button>
+      `,
+    },
+    {
+      code: `
+        <Button popoverOpen='#settings-popover' style={{ width: 'fit-content' }}>
+          {/* should work insinde a component */}
```
Comment (ljharb) [inline tests/lib/rules/jsx-newline.js:119]:
```suggestion
          {/* fake-eslint-disable-next-line should also work inside a component */}
          <Icon f7='gear' />
        </Button>
      `,
    },
    {
      code: `
        <Button popoverOpen='#settings-popover' style={{ width: 'fit-content' }}>
          {/* should work inside a component */}
```

File: lib/rules/jsx-newline.js [hunk 2]
```diff
@@ -72,6 +72,22 @@ module.exports = {
...
+    function findFirstNonBlockComment(index, elements) {
+      if (index >= elements.length) return;
+
+      const element = elements[index];
+      const isElementJSX = element.type === 'JSXElement' || element.type === 'JSXExpressionContainer';
+
+      if (!isBlockCommentInCurlyBraces(element) && isElementJSX) return element;
+
+      return findFirstNonBlockComment(index + 1, elements);
+    }
```
Comment (ljharb) [inline lib/rules/jsx-newline.js:89]: is there a reason to use recursion here rather than `elements.find(predicate)`?

File: lib/rules/jsx-newline.js [hunk 3]
```diff
@@ -93,7 +109,13 @@ module.exports = {
               // Check adjacent sibling has the proper amount of newlines
               const isWithoutNewLine = !/\n\s*\n/.test(firstAdjacentSibling.value);
 
-              if (allowMultilines && (isMultilined(element) || isMultilined(secondAdjacentSibling))) {
+              if (isBlockCommentInCurlyBraces(element)) return;
+
+              if (
+                allowMultilines
+                && (isMultilined(element)
+                  || isMultilined(findFirstNonBlockComment(index + 2, elements)))
```
Comment (ljharb) [inline lib/rules/jsx-newline.js:117]:
```suggestion
                && (
                  isMultilined(element)
                  || isMultilined(findFirstNonBlockComment(index + 2, elements)
                )
              )
```

**Review by ljharb — CHANGES_REQUESTED** [review]
Test cases look great!

File: tests/lib/rules/jsx-newline.js (hunk 1 above)
Comment (justmejulian) [reply tests/lib/rules/jsx-newline.js]: oh ups. thanks!

File: lib/rules/jsx-newline.js (hunk 2 above)
Comment (justmejulian) [reply lib/rules/jsx-newline.js:89]: No didn't think of using find. Let me give it a try.

Comment (justmejulian) [reply lib/rules/jsx-newline.js]: Added a version with `find` please let me no which version you prefer.

**Review by ljharb — APPROVED** [review]
