### PR TITLE
[Fix] `sort-prop-types`: single line type ending without semicolon

### LINKED ISSUE #3783: [Bug]: `sort-prop-types`'s autofix doesn't move the semicolon, producing broken code, on single-line Props types
### Is there an existing issue for this?

- [X] I have searched the existing issues and my issue is unique
- [X] My issue appears in the command-line and not only in the text editor

### Description Overview

`sort-prop-types`, with `checkTypes: true`, breaks the code when run on single-line Props with autofix due to the semicolon staying at the end instead of moving.

image

The props were rearranged without the semicolon dividing them

`eslint --fix`

### Expected Behavior

Semicolon be moved along with the moved prop when running autofix

```tsx
type CustomProps = { onChange: (event: { target: { name: string; value: string } }) => void; name: string };
```

should become

```tsx
type CustomProps = { name: string; onChange: (event: { target: { name: string; value: string } }) => void };
```

Instead, it is fixing to

```tsx
type CustomProps = { name: string onChange: (event: { target: { name: string; value: string } }) => void; };
```

### eslint-plugin-react version

v7.34.4

### eslint version

v8.57.0

### node version

v20.14.10

### PR DESCRIPTION
**Pull request by akulsr0**
Partially fixes #3783

### CODE REVIEW

File: lib/util/propTypesSort.js [hunk 1]
```diff
@@ -197,7 +199,8 @@ function fixPropTypesSort(
             sortedAttrText = attrSource.slice(sortedAttr.range[0], sortedAttr.range[1]);
           }
         }
-        return `${acc.slice(0, commentnodeMap.get(attr).start)}${sortedAttrText}${acc.slice(commentnodeMap.get(attr).end)}`;
+        const sortedAttrTextVal = !checkTypes || sortedAttrText.endsWith(';') ? sortedAttrText : `${sortedAttrText};`;
```
Comment (ljharb) [inline lib/util/propTypesSort.js:202]:
```suggestion
        const sortedAttrTextVal = checkTypes ? sortedAttrText.replace(/;?^/, ';') : sortedAttrText;
```
seems a bit simpler

File: tests/lib/rules/sort-prop-types.js [hunk 2]
```diff
@@ -2325,16 +2325,16 @@ ruleTester.run('sort-prop-types', rule, {
     {
       code: `
         const Foo = (props: {
-          zzz: string,
-          aaa: string,
+          zzz: string;
+          aaa: string;
```
Comment (ljharb) [inline tests/lib/rules/sort-prop-types.js:2329]: let's not change existing test cases - we need to be able to handle any mix of commas and semicolons, since TS types can have both

**Comment by akulsr0** [comment]
@ljharb Failing test looks like a fluke, can we rerun failing test once?

**Comment by ljharb** [comment]
The failures are due to https://github.com/nodejs/node/issues/53902. Once that's resolved, I'll rerun them.

**Review by ljharb — APPROVED** [review]
